name: CI/CD - Docker + ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      ECR_REPOSITORY: devops-fase-2
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build da imagem Docker
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push da imagem para o ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy no ECS
        run: |
          aws ecs update-service \
            --cluster nome-do-cluster-ecs \        # 🔁 Substitua pelo nome real do seu cluster ECS
            --service nome-do-servico-ecs \        # 🔁 Substitua pelo nome real do seu serviço ECS
            --force-new-deployment \
            --region $AWS_REGION
